# ServerStabilitySystem - стабилизатор конфигурации ядра!
# Versions: v-19.05.668

Hex: "Notch"
Error: "§6[!] §cНе нарушайте правила сервера!"
YesPerm: "§6[*] §aИгровой режим успешно изменен!"
NoPerm: "§6[!] §cУ вас нет прав на это!"
