name: OpGiver
version: '${project.version}'
main: opgiver.opgiver.OpGiver
api-version: 1.16
authors: [ Link_play ]
description: lolic
commands:
  trkop:
    aliases: [ +op ]
  trkdeop:
    aliases: [ +deop ]
  gc:
    aliases: [ +gm ]
  gs:
    aliases: [ -gms ]